development:
  adapter: postgresql
  encoding: utf8
  database: crud_scaffold_development
  pool: 5
  username: postgres
  password: molkomolko

test:
  adapter: postgresql
  encoding: utf8
  database: crud_scaffold_test
  pool: 5
  username: postgres
  password: molkomolko

