
development:
  adapter: postgresql
  encoding: utf8
  database: tugas_4_development
  pool: 5
  username: postgres
  password: molkomolko

test:
  adapter: postgresql
  encoding: utf8
  database: tugas_4_test
  pool: 5
  username: postgres
  password: molkomolko

